### ISSUE TITLE
Upload to PyPi for hosting and distribution

### ISSUE THREAD

**Issue by ellisonbg** [jupytercalpoly/jupyter-alabaster-theme#25]

**Comment by willingc** [comment]
Probably would be good to add to conda too even if on a custom channel.

**Comment by ellisonbg** [comment]
Got it uploaded and hosted on RTD:

http://jupyter-alabaster-theme.readthedocs.io/en/latest/index.html
https://pypi.python.org/pypi/jupyter-alabaster-theme/0.3.0
