### ISSUE TITLE
Review Sphinx Templates

### ISSUE THREAD

**Issue by charnpreetsingh** [jupytercalpoly/jupyter-alabaster-theme#26]
Documentation for this theme is currently in progress. (Expect to have them completed Monday). In the meantime if I could get Sphinx templates code reviewed that would be great!

The following need to be reviewed:
- [x] navbar.html
- [ ] mobile_sidebar.html
- [x] layout.html
- [x] footer.html
- [x] custom_searchbox.html
- [x] custom_search.html
- [x] custom_navigation.html
CC @willingc @ellisonbg

**Comment by ellisonbg** [comment]
I have reviewed them and cleaned things up. Closing.
