### ISSUE TITLE
Update package URL to point to appropriate readthedocs site hosting jupyter-alabaster-theme docs

### ISSUE THREAD

**Issue by charnpreetsingh** [jupytercalpoly/jupyter-alabaster-theme#38]
This will need to be done after theme documentation is done, repo is moved to Jupyter organization, and hosted on readthedocs.

**Comment by willingc** [comment]
@charnpreetsingh Just to clarify this issue... does this an issue to keep track of:

- [ ] Create theme documentation
- [ ] Move repo from jupytercalpoly to jupyter org
- [ ] Update any links in theme documentation to reference the jupyter org repo

**Comment by charnpreetsingh** [comment]
@willingc Yes, but to clarify I mean to update the link in `setup.py`

**Comment by willingc** [comment]
I'll be around on Thursday and Friday morning in SLO if you feel ready to move to the Jupyter org. We can always have a note at the top of the README indicating how ready this is for production use.
