### ISSUE TITLE
Unpin the dependency for Sphinx in requirements

### ISSUE THREAD

**Issue by willingc** [jupytercalpoly/jupyter-alabaster-theme#40]
We would like to use a more recent version of Sphinx. It would be great to either >= or pin to a recent Sphinx version.

**Comment by charnpreetsingh** [comment]
@willingc I was actually thinking about this yesterday. Changing the sphinx version would also affect documentation using an older version (may or may not break their builds)

**Comment by willingc** [comment]
I don't think it would if you specify it as a minimum version as follows: 

```
sphinx>=1.3.6
```
or
```
sphinx>=1.3
```
