### ISSUE TITLE
Update docs for this theme

### ISSUE THREAD

**Issue by ellisonbg** [jupytercalpoly/jupyter-alabaster-theme#55]
We have changed a lot about how this theme works and will need to update the README and documentation for this theme itself.

**Comment by willingc** [comment]
Way to go @ellisonbg for updating the setup. 

@charnpreetsingh Mostly what was changed was:

- removed duplicate file copies that were unmodified to make it easier to track any alabaster updates
- updated how setuptools installs the theme
- changed the process for the theme to grab its version
