### ISSUE TITLE
Review color of highlights

### ISSUE THREAD

**Issue by willingc** [jupytercalpoly/jupyter-alabaster-theme#57]
I've built the JupyterHub docs with this theme and deployed on my test-jupyterhub RTD instance:

http://test-jupyterhub.readthedocs.io/en/doc-theme-jala/api/app.html

I made no changes other than enabling the jupyter-alabaster-theme. Nice job!

There's a lot of "red" highlighting of links. I wonder if we should look at a different color since red evokes warning to me. Maybe blue?

cc/ @cameronoelsen @charnpreetsingh @ellisonbg @minrk 

<img width="1049" alt="screen shot 2017-04-28 at 7 07 52 am" src="https://cloud.githubusercontent.com/assets/2680980/25532337/ecd26792-2be1-11e7-8082-e2165c5a849f.png">

**Comment by minrk** [comment]
for generic literals like that, I would think that using the default text color (dark grey / black) makes the most sense, rather than any color.

**Comment by charnpreetsingh** [comment]
It looks like the color is coming from Bootstrap's `code.less`. I'll have a fix later today. Interestingly, the `sphinx_rtd_theme` does this behavior as well. 

Ex: https://jupyterlab-tutorial.readthedocs.io/en/latest/adding_content.html

**Comment by minrk** [comment]
FWIW, this CSS makes it look a bit more low-key:

```css
code {
  /* disable red, padded code style from bootstrap */
  background-color: transparent;
  padding: 0px;
  color: inherit;
}
```

<img width="929" alt="screen shot 2017-04-28 at 16 52 31" src="https://cloud.githubusercontent.com/assets/151929/25534126/259284ee-2c33-11e7-837c-051a87dc8820.png">
