### ISSUE TITLE
Tag Releases on GitHub 

### ISSUE THREAD

**Issue by charnpreetsingh** [jupytercalpoly/jupyter-alabaster-theme#64]
Whenever we make a release on PyPi, Conda, etc. for the python package, we should also tag the release on GitHub so that if things are broken, code can be compared across versions easily.

**Comment by willingc** [comment]
Yes!!!!

**Comment by willingc** [comment]
It also helps if the documentation for the theme changes between releases.

**Comment by willingc** [comment]
Closing since we're doing this now ;-)
