### ISSUE TITLE
Search results minor refinements

### ISSUE THREAD

**Issue by cameronoelsen** [jupytercalpoly/jupyter-alabaster-theme#8]
The search results page now looks like this:

![screen shot 2017-02-24 at 12 09 26 pm](https://cloud.githubusercontent.com/assets/6437976/23319138/47cb877a-fa8a-11e6-9d71-ecd01371db38.png)

We need to change some of the content on the page to look like this and be consistent with the rest of the documentation:

- Get rid of the h2 header that says 'Search results' under current search bar and instead make it a h1. The h1 should still have the functionality that it currently has that it changes from 'Searching...' to Search results when it is done with the task

- Move the search input back to the side-nav so it is consistent with rest of documentation. Just wondering if we can still have the search string in the input box if we have the search bar in the left nav, @charnpreetsingh?

![screen shot 2017-02-24 at 11 59 33 am](https://cloud.githubusercontent.com/assets/6437976/23319166/5b6ade02-fa8a-11e6-922f-f620fddd0e28.png)

**Comment by charnpreetsingh** [comment]
@cameronoelsen Just tried it out locally. I deleted the  search `form` on the `search` page and left in the `search box` everywhere else. The text stays in the `search box` which is great!

**Comment by charnpreetsingh** [comment]
Moving back to h2 for Search results based on today's meeting
